// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCherUtI8X43HEJZJ88E5UlQW43lmDkCiY',
    appId: '1:552476215766:web:3f1c53715e18257df8fc77',
    messagingSenderId: '552476215766',
    projectId: 'apple-3729c',
    authDomain: 'apple-3729c.firebaseapp.com',
    storageBucket: 'apple-3729c.appspot.com',
    measurementId: 'G-44VWLQ66BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKSjp2uFSbLdOgOQzMTofs3ukGuEf5oTQ',
    appId: '1:552476215766:android:8939676da6977cf0f8fc77',
    messagingSenderId: '552476215766',
    projectId: 'apple-3729c',
    storageBucket: 'apple-3729c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuhNA144ObGAlJMMyeve30twiseQ2BMh4',
    appId: '1:552476215766:ios:4001e19a5711665cf8fc77',
    messagingSenderId: '552476215766',
    projectId: 'apple-3729c',
    storageBucket: 'apple-3729c.appspot.com',
    androidClientId: '552476215766-it8tdrkcsfpph3tl0cqbvcd8t4t3av41.apps.googleusercontent.com',
    iosClientId: '552476215766-tcmijot98tmoip219d53endnbl7bcvlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivahCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuhNA144ObGAlJMMyeve30twiseQ2BMh4',
    appId: '1:552476215766:ios:4001e19a5711665cf8fc77',
    messagingSenderId: '552476215766',
    projectId: 'apple-3729c',
    storageBucket: 'apple-3729c.appspot.com',
    androidClientId: '552476215766-it8tdrkcsfpph3tl0cqbvcd8t4t3av41.apps.googleusercontent.com',
    iosClientId: '552476215766-tcmijot98tmoip219d53endnbl7bcvlo.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivahCom',
  );
}
